[package]
edition = "2021"
name = "ct-jwt"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
jsonwebtoken = "9.3.0"
mini-moka = "0.10.3"
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2.12.2", default-features = false, features = [
  "napi4",
  "serde-json",
] }
napi-derive = "2.12.2"
serde = "1.0.204"
serde_json = "1.0.121"

[build-dependencies]
napi-build = "2.0.1"

[profile.release]
lto = true
strip = "symbols"
