/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class Claims {
  constructor(data: string, expiresInMs: number)
  get data(): string
}
export class JwtClient {
  constructor(secretKey: string)
  static fromBufferKey(secretKey: Buffer): JwtClient
  sign(payload: string, expiresInMs: number): string
  signClaims(claims: Claims): string
  verify(token: string): boolean
  decode(token: string): Claims
}
